'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DNNStuff.SQLViewPro.ExcelReports

    Partial Public Class ExcelTemplateReportSettingsControl

        '''<summary>
        '''lblOutputFileName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOutputFileName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtOutputFileName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOutputFileName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblContainsHeaderRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContainsHeaderRow As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkContainsHeaderRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkContainsHeaderRow As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblDataSheetName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDataSheetName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDataSheetName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDataSheetName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblXlsFileName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblXlsFileName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlXlsFileName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlXlsFileName As Global.DotNetNuke.UI.UserControls.UrlControl

        '''<summary>
        '''lblXlsxFileName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblXlsxFileName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlXlsxFileName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlXlsxFileName As Global.DotNetNuke.UI.UserControls.UrlControl

        '''<summary>
        '''lblDispositionType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDispositionType As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddDispositionType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddDispositionType As Global.System.Web.UI.WebControls.DropDownList
    End Class
End Namespace
