
using System.Web.UI.HtmlControls;
using System;
using System.Diagnostics;
using System.Data;
using System.Web.UI.WebControls;
using Microsoft.VisualBasic;
using System.Collections;
using System.Web.UI;
using System.Web;
using DotNetNuke.UI.UserControls;




//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DNNStuff.SQLViewPro.ExcelReports
{
	
	public partial class ExcelTemplateReportSettingsControl
	{
		
		///<summary>
		///lblOutputFileName control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblOutputFileName;
		
		///<summary>
		///txtOutputFileName control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtOutputFileName;
		
		///<summary>
		///lblContainsHeaderRow control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblContainsHeaderRow;
		
		///<summary>
		///chkContainsHeaderRow control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.CheckBox chkContainsHeaderRow;
		
		///<summary>
		///lblDataSheetName control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblDataSheetName;
		
		///<summary>
		///txtDataSheetName control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtDataSheetName;
		
		///<summary>
		///lblXlsFileName control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblXlsFileName;
		
		///<summary>
		///ctlXlsFileName control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected UrlControl ctlXlsFileName;
		
		///<summary>
		///lblXlsxFileName control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblXlsxFileName;
		
		///<summary>
		///ctlXlsxFileName control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected UrlControl ctlXlsxFileName;
		
		///<summary>
		///lblDispositionType control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblDispositionType;
		
		///<summary>
		///ddDispositionType control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.DropDownList ddDispositionType;
	}
}

