//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("DNNStuff.SQLViewPro")]
[assembly: System.Reflection.AssemblyDescription("DNNStuff.SQLViewPro - DNN7 Install")]
[assembly: System.Reflection.AssemblyCompany("DNNStuff")]
[assembly: System.Reflection.AssemblyProduct("DNNStuff SQLViewPro")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (c) DNNStuff 2017")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyVersion("04.01.01")]
[assembly: System.Reflection.AssemblyFileVersion("04.01.01")]


