

using System;


using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


[assembly:AssemblyTitle("DNNStuff.SQLViewPro")]
[assembly:AssemblyDescription("DNNStuff.SQLViewPro - DNN7 Install - .NET 3.5")]
[assembly:AssemblyCompany("DNNStuff")]
[assembly:AssemblyProduct("DNNStuff SQLViewPro")]
[assembly:AssemblyCopyright("Copyright (c) DNNStuff 2004-2012")]
[assembly:ComVisible(false)]
[assembly:CLSCompliant(true)]
[assembly:AssemblyVersion("04.01.00")]
[assembly:AssemblyFileVersion("04.01.00")]


