'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices
<Assembly: AssemblyTitle("DNNStuff.SQLViewPro"),  _
 Assembly: AssemblyDescription("DNNStuff.SQLViewPro - DNN6 Install - .NET 3.5"),  _
 Assembly: AssemblyCompany("DNNStuff"),  _
 Assembly: AssemblyProduct("DNNStuff SQLViewPro"),  _
 Assembly: AssemblyCopyright("Copyright (c) DNNStuff 2004-2012"),  _
 Assembly: ComVisible(false),  _
 Assembly: CLSCompliant(true),  _
 Assembly: AssemblyVersion("04.00.18"),  _
 Assembly: AssemblyFileVersion("04.00.18")> 

