'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DNNStuff.SQLViewPro

    Partial Public Class EditReportSet

        '''<summary>
        '''lblName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblSkin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSkin As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboSkin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboSkin As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblConnection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblConnection As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeader As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHeader As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFooter As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFooter As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblReports control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReports As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cmdAddReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddReport As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''dgReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgReport As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''lblParameters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblParameters As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cmdAddParameter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddParameter As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''dgParameter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgParameter As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''lblDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDebug As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDebug As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblRunCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRunCaption As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRunCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRunCaption As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblBackCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBackCaption As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtBackCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBackCaption As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblAutoRun control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAutoRun As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAutoRun control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAutoRun As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblAlwaysShowParameters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAlwaysShowParameters As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAlwaysShowParameters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAlwaysShowParameters As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblRenderMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRenderMode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlRenderMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlRenderMode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblParameterLayout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblParameterLayout As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtParameterLayout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtParameterLayout As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
