
using DotNetNuke.Services.Localization;
	using System;
using System.Web;
using System.ComponentModel;
using Microsoft.VisualBasic;
using System.Web.UI.WebControls;
using System.Collections;
using System.Web.UI.HtmlControls;
using System.Web.UI;
using System.Data.SqlClient;
using System.Data;
using DotNetNuke.UI.UserControls;




//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DNNStuff.SQLViewPro
{
	
	public partial class EditReport
	{
		
		///<summary>
		///lblName control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblName;
		
		///<summary>
		///txtName control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtName;
		
		///<summary>
		///lblSkin control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblSkin;
		
		///<summary>
		///cboSkin control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.DropDownList cboSkin;
		
		///<summary>
		///lblQuery control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblQuery;
		
		///<summary>
		///txtQuery control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtQuery;
		
		///<summary>
		///vldQuery control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.CustomValidator vldQuery;
		
		///<summary>
		///cmdQueryTest control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.LinkButton cmdQueryTest;
		
		///<summary>
		///lblQueryTestResults control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.Label lblQueryTestResults;
		
		///<summary>
		///lblConnection control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblConnection;
		
		///<summary>
		///lblCommandCacheTimeout control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblCommandCacheTimeout;
		
		///<summary>
		///txtCommandCacheTimeout control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtCommandCacheTimeout;
		
		///<summary>
		///reqCommandCacheTimeout control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.RequiredFieldValidator reqCommandCacheTimeout;
		
		///<summary>
		///cmpCommandCacheTimeout control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.CompareValidator cmpCommandCacheTimeout;
		
		///<summary>
		///lblCommandCacheScheme control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblCommandCacheScheme;
		
		///<summary>
		///ddCommandCacheScheme control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.DropDownList ddCommandCacheScheme;
		
		///<summary>
		///lblNoItems control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblNoItems;
		
		///<summary>
		///txtNoItems control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtNoItems;
		
		///<summary>
		///lblHeader control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblHeader;
		
		///<summary>
		///txtHeader control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtHeader;
		
		///<summary>
		///lblFooter control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblFooter;
		
		///<summary>
		///txtFooter control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtFooter;
		
		///<summary>
		///lblPageTitle control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblPageTitle;
		
		///<summary>
		///txtPageTitle control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtPageTitle;
		
		///<summary>
		///lblMetaDescription control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblMetaDescription;
		
		///<summary>
		///txtMetaDescription control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtMetaDescription;
		
		///<summary>
		///lblDrilldownReport control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblDrilldownReport;
		
		///<summary>
		///ddDrilldownReportId control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.DropDownList ddDrilldownReportId;
		
		///<summary>
		///lblDrilldownFieldname control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblDrilldownFieldname;
		
		///<summary>
		///txtDrilldownFieldname control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtDrilldownFieldname;
		
		///<summary>
		///lblReportType control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblReportType;
		
		///<summary>
		///ddReportType control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.DropDownList ddReportType;
		
		///<summary>
		///phReportSettings control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.PlaceHolder phReportSettings;
		
		///<summary>
		///cmdUpdate control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.LinkButton cmdUpdate;
		
		///<summary>
		///cmdCancel control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.LinkButton cmdCancel;
	}
}

