'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DNNStuff.SQLViewPro

    Partial Public Class EditReport

        '''<summary>
        '''lblName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblSkin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSkin As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboSkin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboSkin As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblQuery control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblQuery As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cmdQueryTest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdQueryTest As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''txtQuery control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtQuery As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''vldQuery control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vldQuery As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''lblQueryTestResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblQueryTestResults As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblConnection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblConnection As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblCommandCacheTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCommandCacheTimeout As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCommandCacheTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCommandCacheTimeout As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''reqCommandCacheTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents reqCommandCacheTimeout As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''cmpCommandCacheTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmpCommandCacheTimeout As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''lblNoItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoItems As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtNoItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNoItems As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeader As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHeader As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFooter As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFooter As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPageTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPageTitle As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtPageTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPageTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblMetaDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMetaDescription As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtMetaDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMetaDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblDrilldownReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDrilldownReport As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddDrilldownReportId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddDrilldownReportId As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblDrilldownFieldname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDrilldownFieldname As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDrilldownFieldname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDrilldownFieldname As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblReportType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportType As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddReportType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddReportType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''phReportSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phReportSettings As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
