
using DotNetNuke.Services.Localization;
	using System;
using System.Web;
using System.ComponentModel;
using Microsoft.VisualBasic;
using System.Web.UI.WebControls;
using System.Collections;
using System.Web.UI.HtmlControls;
using System.Web.UI;
using System.Data.SqlClient;
using System.Data;
using DotNetNuke.UI.UserControls;




//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DNNStuff.SQLViewPro
{
	
	public partial class EditReportSet
	{
		
		///<summary>
		///lblName control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblName;
		
		///<summary>
		///txtName control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtName;
		
		///<summary>
		///lblSkin control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblSkin;
		
		///<summary>
		///cboSkin control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.DropDownList cboSkin;
		
		///<summary>
		///lblConnection control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblConnection;
		
		///<summary>
		///lblHeader control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblHeader;
		
		///<summary>
		///txtHeader control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtHeader;
		
		///<summary>
		///lblFooter control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblFooter;
		
		///<summary>
		///txtFooter control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtFooter;
		
		///<summary>
		///lblReports control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblReports;
		
		///<summary>
		///cmdAddReport control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.LinkButton cmdAddReport;
		
		///<summary>
		///dgReport control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.DataGrid dgReport;
		
		///<summary>
		///lblParameters control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblParameters;
		
		///<summary>
		///cmdAddParameter control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.LinkButton cmdAddParameter;
		
		///<summary>
		///dgParameter control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.DataGrid dgParameter;
		
		///<summary>
		///lblDebug control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblDebug;
		
		///<summary>
		///chkDebug control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.CheckBox chkDebug;
		
		///<summary>
		///lblRunCaption control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblRunCaption;
		
		///<summary>
		///txtRunCaption control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtRunCaption;
		
		///<summary>
		///lblBackCaption control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblBackCaption;
		
		///<summary>
		///txtBackCaption control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtBackCaption;
		
		///<summary>
		///lblAutoRun control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblAutoRun;
		
		///<summary>
		///chkAutoRun control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.CheckBox chkAutoRun;
		
		///<summary>
		///lblAlwaysShowParameters control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblAlwaysShowParameters;
		
		///<summary>
		///chkAlwaysShowParameters control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.CheckBox chkAlwaysShowParameters;
		
		///<summary>
		///lblRenderMode control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblRenderMode;
		
		///<summary>
		///ddlRenderMode control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.DropDownList ddlRenderMode;
		
		///<summary>
		///lblParameterLayout control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblParameterLayout;
		
		///<summary>
		///txtParameterLayout control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtParameterLayout;
		
		///<summary>
		///cmdUpdate control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.LinkButton cmdUpdate;
		
		///<summary>
		///cmdCancel control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.LinkButton cmdCancel;
	}
}

