'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DNNStuff.SQLViewPro.MobileParameters

    Partial Public Class MobiscrollParameterSettingsControl

        '''<summary>
        '''lblDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDefault As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDefault As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPreset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPreset As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddPreset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddPreset As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblTheme control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTheme As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddTheme control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddTheme As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddMode As Global.System.Web.UI.WebControls.DropDownList
    End Class
End Namespace
