
using DotNetNuke.Services.Localization;
	using System;
using System.Web;
using System.ComponentModel;
using Microsoft.VisualBasic;
using System.Web.UI.WebControls;
using System.Collections;
using System.Web.UI.HtmlControls;
using System.Web.UI;
using System.Data.SqlClient;
using System.Data;



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DNNStuff.SQLViewPro.Controls
{
	
	///<summary>
	///ConnectionPickerControl class.
	///</summary>
	///<remarks>
	///Auto-generated class.
	///</remarks>
	public partial class ConnectionPickerControl
	{
		
		///<summary>
		///ddlConnectionPicker control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.DropDownList ddlConnectionPicker;
	}
}

