'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DNNStuff.SQLViewPro.SSRSReports

    Partial Public Class SSRSReportSettingsControl

        '''<summary>
        '''lblProcessingMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProcessingMode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlProcessingMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlProcessingMode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlRemote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlRemote As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblReportServerUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportServerUrl As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtReportServerUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReportServerUrl As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblReportServerReportPath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportServerReportPath As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtReportServerReportPath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReportServerReportPath As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblReportServerUsername control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportServerUsername As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtReportServerUsername control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReportServerUsername As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblReportServerPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportServerPassword As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtReportServerPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReportServerPassword As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblReportServerDomain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportServerDomain As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtReportServerDomain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReportServerDomain As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''pnlLocal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlLocal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblLocalReportPath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLocalReportPath As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''urlLocalReportPath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents urlLocalReportPath As Global.DotNetNuke.UI.UserControls.UrlControl

        '''<summary>
        '''lblAdditionalParameters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAdditionalParameters As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAdditionalParameters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAdditionalParameters As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblViewerWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblViewerWidth As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtViewerWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtViewerWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblViewerHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblViewerHeight As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtViewerHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtViewerHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblReportOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportOptions As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lstReportOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstReportOptions As Global.System.Web.UI.WebControls.CheckBoxList
    End Class
End Namespace
