
using System.Collections;
using System;
using System.Diagnostics;
using Microsoft.VisualBasic;
using System.Data;



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DNNStuff.SQLViewPro.StandardParameters
{
	
	///<summary>
	///ListBoxParameterControl class.
	///</summary>
	///<remarks>
	///Auto-generated class.
	///</remarks>
	public partial class ListBoxParameterControl
	{
		
		///<summary>
		///lbParameter control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.ListBox lbParameter;
	}
}

