'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DNNStuff.SQLViewPro.StandardParameters

    Partial Public Class FlowListParameterSettingsControl

        '''<summary>
        '''lblDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDefault As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDefault As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblRepeatColumns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRepeatColumns As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRepeatColumns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRepeatColumns As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblRepeatDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRepeatDirection As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlRepeatDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlRepeatDirection As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblRepeatLayout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRepeatLayout As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlRepeatLayout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlRepeatLayout As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblList As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtList As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblConnection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblConnection As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblCommand control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCommand As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCommand control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCommand As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''vldCommand control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vldCommand As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''lblCommandCacheTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCommandCacheTimeout As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCommandCacheTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCommandCacheTimeout As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''reqCommandCacheTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents reqCommandCacheTimeout As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''cmpCommandCacheTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmpCommandCacheTimeout As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''cmdQueryTest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdQueryTest As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblQueryTestResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblQueryTestResults As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
