'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DNNStuff.SQLViewPro.StandardParameters

    Partial Public Class GeoLocationParameterSettingsControl

        '''<summary>
        '''lblEnableHighAccuracy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnableHighAccuracy As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnableHighAccuracy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableHighAccuracy As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTimeout As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTimeout As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtTimeoutRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTimeoutRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtTimeoutInteger control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTimeoutInteger As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''lblMaximumAge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMaximumAge As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtMaximumAge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaximumAge As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMaximumAgeRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaximumAgeRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtMaximumAgeInteger control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaximumAgeInteger As Global.System.Web.UI.WebControls.CompareValidator
    End Class
End Namespace
