
using System.Collections;
using System;
using System.Diagnostics;
using Microsoft.VisualBasic;
using System.Data;
using DotNetNuke.UI.UserControls;




//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DNNStuff.SQLViewPro.StandardParameters
{
	
	public partial class GeoLocationParameterSettingsControl
	{
		
		///<summary>
		///lblEnableHighAccuracy control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblEnableHighAccuracy;
		
		///<summary>
		///chkEnableHighAccuracy control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.CheckBox chkEnableHighAccuracy;
		
		///<summary>
		///lblTimeout control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblTimeout;
		
		///<summary>
		///txtTimeout control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtTimeout;
		
		///<summary>
		///txtTimeoutRequired control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.RequiredFieldValidator txtTimeoutRequired;
		
		///<summary>
		///txtTimeoutInteger control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.CompareValidator txtTimeoutInteger;
		
		///<summary>
		///lblMaximumAge control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected LabelControl lblMaximumAge;
		
		///<summary>
		///txtMaximumAge control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.TextBox txtMaximumAge;
		
		///<summary>
		///txtMaximumAgeRequired control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.RequiredFieldValidator txtMaximumAgeRequired;
		
		///<summary>
		///txtMaximumAgeInteger control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected System.Web.UI.WebControls.CompareValidator txtMaximumAgeInteger;
	}
}

