'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DNNStuff.SQLViewPro.SSRSReports

    Partial Public Class SSRSReportControl

        '''<summary>
        '''ReportViewer1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReportViewer1 As Global.Microsoft.Reporting.WebForms.ReportViewer
    End Class
End Namespace
