'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DNNStuff.SQLViewPro.StandardReports

    Partial Public Class GridReportSettingsControl

        '''<summary>
        '''lblAllowSorting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllowSorting As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAllowSorting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllowSorting As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblOrderBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOrderBy As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtOrderBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOrderBy As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblAllowPaging control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllowPaging As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAllowPaging control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllowPaging As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPageSize As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPageSize As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPagerMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPagerMode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddPagerMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddPagerMode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblPrevNext control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPrevNext As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtPrevPageText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPrevPageText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNextPageText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNextPageText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPagerPosition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPagerPosition As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddPagerPosition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddPagerPosition As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblEnableExcelExport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnableExcelExport As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnableExcelExport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableExcelExport As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblExcelExportCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExcelExportCaption As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtExcelExportButtonCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExcelExportButtonCaption As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblExcelExportPosition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExcelExportPosition As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddExcelExportPosition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddExcelExportPosition As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblHideColumnHeaders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHideColumnHeaders As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkHideColumnHeaders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideColumnHeaders As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblHideColumns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHideColumns As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtHideColumns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHideColumns As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
