//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNNStuff.SQLViewPro.StandardReports {
    
    
    public partial class TemplateReportSettingsControl {
        
        /// <summary>
        /// lblTemplateText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected DotNetNuke.UI.UserControls.LabelControl lblTemplateText;
        
        /// <summary>
        /// txtTemplateText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox txtTemplateText;
        
        /// <summary>
        /// lblAllowPaging control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected DotNetNuke.UI.UserControls.LabelControl lblAllowPaging;
        
        /// <summary>
        /// chkAllowPaging control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected System.Web.UI.WebControls.CheckBox chkAllowPaging;
        
        /// <summary>
        /// lblPagingType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected DotNetNuke.UI.UserControls.LabelControl lblPagingType;
        
        /// <summary>
        /// ddPagingType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected System.Web.UI.WebControls.DropDownList ddPagingType;
        
        /// <summary>
        /// lblPageSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected DotNetNuke.UI.UserControls.LabelControl lblPageSize;
        
        /// <summary>
        /// txtPageSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox txtPageSize;
        
        /// <summary>
        /// lblPrevNext control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected DotNetNuke.UI.UserControls.LabelControl lblPrevNext;
        
        /// <summary>
        /// txtPrevPageText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox txtPrevPageText;
        
        /// <summary>
        /// txtNextPageText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox txtNextPageText;
        
        /// <summary>
        /// lblFirstLast control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected DotNetNuke.UI.UserControls.LabelControl lblFirstLast;
        
        /// <summary>
        /// txtFirstPageText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox txtFirstPageText;
        
        /// <summary>
        /// txtLastPageText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox txtLastPageText;
        
        /// <summary>
        /// lblPageTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected DotNetNuke.UI.UserControls.LabelControl lblPageTemplate;
        
        /// <summary>
        /// txtPageTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected System.Web.UI.WebControls.TextBox txtPageTemplate;
    }
}
