'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DNNStuff.SQLViewPro.StandardReports

    Partial Public Class XmlReportSettingsControl

        '''<summary>
        '''lblXslSrc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblXslSrc As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtXslSrc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtXslSrc As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
